### ISSUE TITLE
[PE-D][Tester C] Undo command always returns back to list all members and events

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F11-1/tp#232] opened 2023-11-03 22:00 UTC
![image.png](https://raw.githubusercontent.com/Singa-pirate/ped/main/files/f6b19cfc-d0b4-4d59-b4e5-5b66d7bfcd8b.png)

Now, the only enrolment is member 1 - event 1.
After unenrolling m1-e1:

![image.png](https://raw.githubusercontent.com/Singa-pirate/ped/main/files/8fe58c98-cd19-4885-9d28-0dd8b6c83324.png)

After undoing:

![image.png](https://raw.githubusercontent.com/Singa-pirate/ped/main/files/3c14b382-5bc6-498d-b1d8-62f7351600b1.png)

This actually lists all members and events, but as a user, I may be confused to think that member 2 is enrolled to event 1, which is not what I expect.

I suggest `undo` and `redo` command can apply the same filtering conditions on the displayed list as before, rather than always listing everything. In that way, it's also more clear what has been undone/redone especially for undoing/redoing `enrol` or `unenrol` commands.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Singa-pirate/ped#7

**Comment by wr1159** [comment] 2023-11-05 15:45
Bug is duplicate of #227,

Accepted feature flaw that undo and redo should apply the same filtering conditions on the displayed list before.

To Change:
* Add into planned enhancements to include applying same filtering conditions in commands

**Closed as completed** 2023-11-09 04:17 UTC
Labels: type.FeatureFlaw
